export interface DailyBriefEmailTemplateInput {
  date: string;
  focusSummary: string;
  upcomingEvents: { title: string; time?: string; description?: string }[];
  importantTasks: string[];
  notes: string[];
  highlights?: string[];
  summary?: string;
}

/**
 * Render the Daily Brief email template.
 * Sections: Today's Focus, Upcoming Events, Important Tasks, Notes.
 */
export function renderDailyBriefEmail(data: DailyBriefEmailTemplateInput): string {
  const formatList = (items: string[], emptyCopy: string): string =>
    items.length > 0
      ? items.map((item) => `<li>${item}</li>`).join('')
      : `<li class="muted">${emptyCopy}</li>`;

  const formatEventList = (
    events: { title: string; time?: string; description?: string }[],
    emptyCopy: string
  ): string =>
    events.length > 0
      ? events
          .map(
            (event) =>
              `<li><strong>${event.title}</strong>${event.time ? ` - ${event.time}` : ''}${
                event.description ? `<div class="muted">${event.description}</div>` : ''
              }</li>`
          )
          .join('')
      : `<li class="muted">${emptyCopy}</li>`;

  return `
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Daily Brief - ${data.date}</title>
        <style>
          body { font-family: Arial, sans-serif; color: #1f2933; background: #f5f7fa; margin: 0; padding: 0; }
          .container { max-width: 640px; margin: 0 auto; padding: 24px; }
          .card { background: #ffffff; border-radius: 12px; box-shadow: 0 10px 30px rgba(0, 0, 0, 0.06); overflow: hidden; }
          .header { padding: 24px; background: linear-gradient(135deg, #0f62fe, #6ea8fe); color: #ffffff; }
          .header h1 { margin: 0 0 8px; font-size: 24px; letter-spacing: 0.4px; }
          .header p { margin: 0; opacity: 0.9; }
          .section { padding: 20px 24px; border-bottom: 1px solid #eef1f5; }
          .section:last-child { border-bottom: none; }
          .section h2 { margin: 0 0 10px; font-size: 18px; color: #0f172a; }
          .section p { margin: 0 0 10px; line-height: 1.6; }
          ul { margin: 0; padding-left: 18px; }
          li { margin: 6px 0; line-height: 1.5; }
          .muted { color: #6b7280; font-size: 14px; }
          .footer { padding: 16px 24px 20px; background: #f9fafb; color: #6b7280; font-size: 12px; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="card">
            <div class="header">
              <p>Daily Brief</p>
              <h1>${data.date}</h1>
              ${data.summary ? `<p>${data.summary}</p>` : ''}
            </div>

            <div class="section">
              <h2>Today's Focus</h2>
              <p>${data.focusSummary}</p>
              ${
                data.highlights && data.highlights.length > 0
                  ? `<ul>${formatList(data.highlights, 'No highlights noted.')}</ul>`
                  : ''
              }
            </div>

            <div class="section">
              <h2>Upcoming Events</h2>
              <ul>${formatEventList(data.upcomingEvents, 'No events scheduled yet.')}</ul>
            </div>

            <div class="section">
              <h2>Important Tasks</h2>
              <ul>${formatList(data.importantTasks, 'No tasks added. Focus on your top priority.')}</ul>
            </div>

            <div class="section">
              <h2>Notes</h2>
              <ul>${formatList(data.notes, 'No additional notes for today.')}</ul>
            </div>

            <div class="footer">
              <p>Generated by the Elevated Movements Daily Brief agent.</p>
            </div>
          </div>
        </div>
      </body>
    </html>
  `;
}
